const  CryptoData = [
  {
      id: 1,
      name: "بیتکوین",
      pair: "BTC / USDT",
      value: "0.6359",
      percentage: "-2.58",
      transactions: "24.9B",
    },  {
        id: 2,
        name: "اتریوم",
        pair: "ETH / USDT",
        value: "10.6359",
        percentage: "-2.58",
        transactions: "24.9B",
      },  {
        id: 3,
        name: "بایننس کوین",
        pair: "BNB / USDT",
        value: "23.6359",
        percentage: "-2.58",
        transactions: "24.9B",
      },  {
        id: 4,
        name: "ریپل",
        pair: "XRP / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "34.5B",
      },  {
        id: 5,
        name: "یو اس دی کوین",
        pair: "USDC / USDT",
        value: "5.1239",
        percentage: "-2.58",
        transactions: "41.9B",
      },  {
        id: 6,
        name: "ریپل",
        pair: "XRP / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "14.9B",
      },  {
        id: 7,
        name: "کاردانو",
        pair: "ADA / USDT",
        value: "10.59",
        percentage: "-2.58",
        transactions: "124.9B",
      },  {
        id: 8,
        name: "چین لینک",
        pair: "LINK / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "4.9B",
      },  {
        id: 9,
        name: "اولنج",
        pair: "AVAX / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "24.9B",
      },  {
        id: 10,
        name: "دوج کوین",
        pair: "BTC / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "84.9B",
      },  {
        id: 11,
        name: "ترون",
        pair: "BTC / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "94.9B",
      },  {
        id: 12,
        name: "سولانا",
        pair: "BTC / USDT",
        value: "0.6359",
        percentage: "-2.58",
        transactions: "11.9B",
      },
  
  ]
  export default CryptoData;